config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount ActionCable.server, at: '/cable'

  root 'pages#home'
  get 'pages/home'
  get 'dashboard', to: 'dashboard#index'

  devise_for :physicians, controllers: { sessions: 'physicians/sessions' }
  devise_for :patients, controllers: {
    sessions: 'patients/sessions',
    registrations: 'patients/registrations'
  }

  resources :appointments
  resources :conversations do
    resources :messages
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
# frozen_string_literal: true

class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :physician
  has_and_belongs_to_many :diseases

  validates :date, :time, presence: true
  enum status: { pending: 0, canceled: 1, rejected: 2, accepted: 3, attended: 4 }

  def conversation
    Conversation.find_or_create_by(patient: patient, physician: physician)
  end
end

app/models/conversation.rb
# frozen_string_literal: true

class Conversation < ApplicationRecord
  belongs_to :patient
  belongs_to :physician
  has_many :messages, dependent: :destroy
end

app/models/disease.rb
# frozen_string_literal: true

class Disease < ApplicationRecord
  SYMPTOMS = %w[nausea coughing rash insomnia cysts vomiting sneezing sweating hyper_sensitivity abscesses tumours
                diarrhoea skin_lesions seizures hemorrhagic_shock]

  has_and_belongs_to_many :appointments

  scope :by_symptoms, ->(symptoms) { where('symptoms @> Array[?]::varchar[]', symptoms) if symptoms&.any? }
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user, polymorphic: true
  belongs_to :conversation

  validates :content, presence: true
end

app/models/parent.rb
# frozen_string_literal: true

class Parent < ApplicationRecord
  belongs_to :patient
  validates :name, :surname, presence: true
end

app/models/patient.rb
# frozen_string_literal: true

class Patient < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  has_one :parent, dependent: :destroy
  has_many :conversations, dependent: :destroy
  has_many :messages, as: :user, dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_many :physicians, through: :appointments

  accepts_nested_attributes_for :parent

  validates :name, :surname, :email, :age, :blood_type, presence: true
end

app/models/physician.rb
# frozen_string_literal: true

class Physician < ApplicationRecord
  devise :database_authenticatable,
         :rememberable,
         :validatable,
         :trackable

  has_many :conversations, dependent: :destroy
  has_many :messages, as: :user, dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments

  def full_name
    "#{name} #{surname}"
  end
end

app/controllers/application_controller.rb
require 'application_responder'

# frozen_string_literal: true

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :json, :js

  include Pundit
  include Accessible
  protect_from_forgery
  before_action :require_login
  before_action :configure_permitted_parameters, if: :devise_controller?

  expose :current_user, -> { current_physician || current_patient }

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:email, :password, :password_confirmation, :name, :surname, :weight,
                                             :height, :age, :blood_type, parent_attributes: %i[name surname]])
  end
end

app/controllers/appointments_controller.rb
# frozen_string_literal: true

class AppointmentsController < ApplicationController
  expose :appointment
  expose :appointments, -> { current_user.appointments }
  expose :appointment_physicians, -> { Physician.all }
  expose :appointment_statuses, -> { Appointment.statuses.keys }
  expose :physicians, -> { Physician.all }
  expose :conversation, -> { Conversation.find_by(patient: appointment.patient, physician: appointment.physician) }

  def create
    authorize(appointment, :create?)
    appointment.patient = current_patient
    assign_diseases
    return redirect_to appointment_path(appointment) if appointment.save

    render :new
  end

  def update
    authorize(appointment, :update?)
    return redirect_to appointment_path(appointment) if appointment.update(appointment_params)

    render edit_appointment_path(appointment)
  end

  private

  def assign_diseases
    diseases = Disease.by_symptoms(appointment_params[:symptoms].reject(&:empty?))
    appointment.diseases << diseases if diseases.any?
  end

  def appointment_params
    params.require(:appointment).permit(:physician_id, :date, :time, :status, :diagnose, symptoms: [])
  end
end

app/controllers/concerns/accessible.rb
# frozen_string_literal: true

module Accessible
  extend ActiveSupport::Concern

  protected

  def require_login
    return if current_physician || current_patient

    flash.clear
    redirect_to(root_path)
  end

  def redirect_signed_in_user
    return unless physician_signed_in? || patient_signed_in?

    flash.clear
    redirect_to(appointments_path)
  end

  def authenticate_admin
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == 'password'
    end
    warden.custom_failure! if performed?
  end
end

app/controllers/conversations_controller.rb
# frozen_string_literal: true

class ConversationsController < ApplicationController
  expose :conversation
  expose :conversations, -> { current_user.conversations }
  expose :message, parent: :conversation, id: :message_id
  expose :last_message, -> { conversation.messages.last }
  expose :messages, -> { conversation.messages }
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController; end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  expose :message
  expose :conversation, -> { Conversation.find(params[:conversation_id]) }

  def create
    return unless message.save

    ConversationChannel.broadcast_to conversation, render_to_string(partial: 'conversations/shared/message',
                                                                    locals: { message: message })
  end

  private

  def message_params
    params.require(:message)
          .permit(:content, :conversation_id)
          .merge(user: current_user)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  before_action :redirect_signed_in_user
  skip_before_action :require_login

  def home; end
end

app/controllers/patients/sessions_controller.rb
# frozen_string_literal: true

class Patients::SessionsController < Devise::SessionsController
  before_action :redirect_signed_in_user, except: :destroy
  skip_before_action :require_login, except: :destroy

  def destroy
    super
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/appointments_helper.rb
# frozen_string_literal: true

module AppointmentsHelper
  def symptom_checkboxes
    Disease::SYMPTOMS.map { |d| [d, d.humanize] }
  end

  def appointment_date
    Date.tomorrow
  end

  def appointment_time
    3.hours.from_now
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/devise_helper.rb
# frozen_string_literal: true

module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, 'error')} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/physicians/dashboard_helper.rb
# frozen_string_literal: true

module Physicians::DashboardHelper
end

app/views/conversations/index.slim
.container-fluid.px-0
  - if conversations.any?
    ul.list-group.list-group-flush
      = render partial: 'conversations/shared/conversation', collection: conversations
  - else
    .text-center.mt-5
      h1.h3.font-weight-light Your conversation history is empty yet...

app/views/conversations/shared/_conversation.slim
li.list-group-item.list-group-item-action
  - if current_patient
    = link_to conversation_path(conversation) do
      .row
        .col-1
          = image_tag conversation.physician.photo, size: '100', alt: 'user-thumbnail', class: 'rounded-circle' if conversation.physician.photo.present?
        .col.text-muted.d-flex.flex-column.align-items-start.justify-content-center.ml-5
          h6.mb-1 = conversation.physician.email
          p.mb-1 = conversation.messages&.last&.content || 'Message history is empty'
        .col-auto
          small = conversation.messages&.last&.created_at&.strftime("%I:%M%p")
          br
          span.badge.badge-pill.badge-primary = conversation.messages.count
  - if current_physician
    = link_to conversation_path(conversation) do
      .row
        .col-1
          = image_tag conversation.patient.photo, size: '100', alt: 'user-thumbnail', class: 'rounded-circle' if conversation.patient.photo
        .col.text-muted
          = conversation.patient.email
        .col-1
          span.badge.badge-pill.badge-primary 10

app/views/conversations/shared/_message.slim
.container.message.mt-3
  .row
    .col-auto.px-1
      small data-role="sender-email" = message.user.email
      span = ' '
      small data-role="sent_at" = message.created_at
  .row
    .col.border.rounded.bg-white.p-2 data-role="message-content" = message.content

app/views/conversations/shared/_new_message.slim
= simple_form_for [message.conversation, message], method: :post, remote: true do |f|
  = f.input :content, required: true, disable: true, label: false
  = f.input :conversation_id, as: :hidden
  = f.submit 'Send', class: 'btn btn-primary btn-md'

app/views/conversations/show.slim
div.container.mt-4 data-channel-subscribe="conversation" data-conversation-id="#{conversation.id}"
  h4.text-center.font-weight-light.pb-3 Beginning of the conversation history...
  #message-list
    = render partial: 'conversations/shared/message', collection: messages
  .mt-3 = render partial: 'conversations/shared/new_message'