config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount ActionCable.server, at: '/cable'

  root 'pages#home'
  get 'pages/home'
  get 'dashboard', to: 'dashboard#index'

  devise_for :physicians, controllers: { sessions: 'physicians/sessions' }
  devise_for :patients, controllers: {
    sessions: 'patients/sessions',
    registrations: 'patients/registrations'
  }

  resources :appointments
  resources :conversations do
    resources :messages
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
# frozen_string_literal: true

class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :physician
  has_and_belongs_to_many :diseases

  validates :date, :time, presence: true
  enum status: { pending: 0, canceled: 1, rejected: 2, accepted: 3, attended: 4 }

  def conversation
    Conversation.find_or_create_by(patient: patient, physician: physician)
  end
end

app/models/conversation.rb
# frozen_string_literal: true

class Conversation < ApplicationRecord
  belongs_to :patient
  belongs_to :physician
  has_many :messages, dependent: :destroy
end

app/models/disease.rb
# frozen_string_literal: true

class Disease < ApplicationRecord
  SYMPTOMS = %w[nausea coughing rash insomnia cysts vomiting sneezing sweating hyper_sensitivity abscesses tumours
                diarrhoea skin_lesions seizures hemorrhagic_shock]

  has_and_belongs_to_many :appointments

  scope :by_symptoms, ->(symptoms) { where('symptoms @> Array[?]::varchar[]', symptoms) if symptoms&.any? }
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user, polymorphic: true
  belongs_to :conversation

  validates :content, presence: true
end

app/models/parent.rb
# frozen_string_literal: true

class Parent < ApplicationRecord
  belongs_to :patient
  validates :name, :surname, presence: true
end

app/models/patient.rb
# frozen_string_literal: true

class Patient < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  has_one :parent, dependent: :destroy
  has_many :conversations, dependent: :destroy
  has_many :messages, as: :user, dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_many :physicians, through: :appointments

  accepts_nested_attributes_for :parent

  validates :name, :surname, :email, :age, :blood_type, presence: true
end

app/models/physician.rb
# frozen_string_literal: true

class Physician < ApplicationRecord
  devise :database_authenticatable,
         :rememberable,
         :validatable,
         :trackable

  has_many :conversations, dependent: :destroy
  has_many :messages, as: :user, dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments

  def full_name
    "#{name} #{surname}"
  end
end

app/controllers/application_controller.rb
require 'application_responder'

# frozen_string_literal: true

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :json, :js

  include Pundit
  include Accessible
  protect_from_forgery
  before_action :require_login
  before_action :configure_permitted_parameters, if: :devise_controller?

  expose :current_user, -> { current_physician || current_patient }

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:email, :password, :password_confirmation, :name, :surname, :weight,
                                             :height, :age, :blood_type, parent_attributes: %i[name surname]])
  end
end

app/controllers/appointments_controller.rb
# frozen_string_literal: true

class AppointmentsController < ApplicationController
  expose :appointment
  expose :appointments, -> { current_user.appointments }
  expose :appointment_physicians, -> { Physician.all }
  expose :appointment_statuses, -> { Appointment.statuses.keys }
  expose :physicians, -> { Physician.all }
  expose :conversation, -> { Conversation.find_by(patient: appointment.patient, physician: appointment.physician) }

  def create
    authorize(appointment, :create?)
    appointment.patient = current_patient
    assign_diseases
    return redirect_to appointment_path(appointment) if appointment.save

    render :new
  end

  def update
    authorize(appointment, :update?)
    return redirect_to appointment_path(appointment) if appointment.update(appointment_params)

    render edit_appointment_path(appointment)
  end

  private

  def assign_diseases
    diseases = Disease.by_symptoms(appointment_params[:symptoms].reject(&:empty?))
    appointment.diseases << diseases if diseases.any?
  end

  def appointment_params
    params.require(:appointment).permit(:physician_id, :date, :time, :status, :diagnose, symptoms: [])
  end
end

app/controllers/concerns/accessible.rb
# frozen_string_literal: true

module Accessible
  extend ActiveSupport::Concern

  protected

  def require_login
    return if current_physician || current_patient

    flash.clear
    redirect_to(root_path)
  end

  def redirect_signed_in_user
    return unless physician_signed_in? || patient_signed_in?

    flash.clear
    redirect_to(appointments_path)
  end

  def authenticate_admin
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == 'password'
    end
    warden.custom_failure! if performed?
  end
end

app/controllers/conversations_controller.rb
# frozen_string_literal: true

class ConversationsController < ApplicationController
  expose :conversation
  expose :conversations, -> { current_user.conversations }
  expose :message, parent: :conversation, id: :message_id
  expose :last_message, -> { conversation.messages.last }
  expose :messages, -> { conversation.messages }
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController; end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  expose :message
  expose :conversation, -> { Conversation.find(params[:conversation_id]) }

  def create
    return unless message.save

    ConversationChannel.broadcast_to conversation, render_to_string(partial: 'conversations/shared/message',
                                                                    locals: { message: message })
  end

  private

  def message_params
    params.require(:message)
          .permit(:content, :conversation_id)
          .merge(user: current_user)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  before_action :redirect_signed_in_user
  skip_before_action :require_login

  def home; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/appointments_helper.rb
# frozen_string_literal: true

module AppointmentsHelper
  def symptom_checkboxes
    Disease::SYMPTOMS.map { |d| [d, d.humanize] }
  end

  def appointment_date
    Date.tomorrow
  end

  def appointment_time
    3.hours.from_now
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/devise_helper.rb
# frozen_string_literal: true

module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, 'error')} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title HK
    = action_cable_meta_tag
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application'
  body
    div class=(current_user ? "border-bottom sticky-top" : "") = render partial: 'layouts/shared/navbar'
    .container-fluid = yield

app/views/layouts/application.slim
doctype html
html
  head
    title
      | Health Keeper
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    - if current_patient || current_physician
      .border-bottom.sticky-top = render partial: 'layouts/shared/navbar'
    = render partial: 'layouts/shared/messages'
    .container-fluid
      = yield

app/views/layouts/shared/_messages.slim
- flash.each do |key, value|
  div class=("alert alert-#{key} m-0")
    a.close[href="#" data-dismiss="alert"]
      | ×
    ul.m-0
      li
        = value

app/views/layouts/shared/_navbar.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to root_path, class: 'navbar-brand d-flex align-items-center' do
    | Health Keeper
    / = image_tag asset_pack_path('first-aid-kit.svg', size: '35', alt: 'navbar-brand-logo', class: 'navbar-brand')
  button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"]
    span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      - if current_user
        li.nav-item = link_to 'Appoinments', appointments_path, class: 'nav-link'
        li.nav-item = link_to 'Conversations', conversations_path, class: 'nav-link'
    ul.navbar-nav
      li.navbar-text.mx-lg-1
        = "#{current_user.name} #{current_user.surname}, #{current_user.email}" if current_user
      li.navbar-item.mx-lg-1
        = link_to 'New appointment', new_appointment_path, class: 'btn btn-success' if current_patient
      li.nav-item
        = link_to "Sign out", destroy_patient_session_path, method: :delete, class: 'btn btn-danger' if current_patient
        = link_to "Sign out", destroy_physician_session_path, method: :delete, class: 'btn btn-danger' if current_physician
      - unless current_user
        li.nav-item = link_to 'Sign in', new_patient_session_path, class: 'nav-link'
        li.nav-item = link_to 'Sign up', new_patient_registration_path, class: 'nav-link'

app/views/pages/home.slim
.row.justify-content-center.align-items-center.public-page.user-select-none
  .col-auto.text-center
    h1.display-3 Welcome to Health Keeper
    h1.display-4 We keep you Up